// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebHomestay.Data;

#nullable disable

namespace WebHomestay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514104415_AddAIBrainCenter")]
    partial class AddAIBrainCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebHomestay.Models.AIAgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.HasKey("Id");

                    b.ToTable("ai_agent_definitions", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIBrainScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.ToTable("ai_brain_scopes", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIConversationTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_message");

                    b.Property<string>("FinalAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_answer");

                    b.Property<string>("GraphReasoningJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("graph_reasoning_json");

                    b.Property<string>("GuardResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guard_result");

                    b.Property<string>("LiveSystemSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("live_system_snapshot");

                    b.Property<string>("ModelProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_provider");

                    b.Property<string>("PersonaSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_summary");

                    b.Property<string>("RetrievedKnowledgeJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retrieved_knowledge_json");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.ToTable("ai_conversation_traces", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIGraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_node_id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_node_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("ai_graph_edges", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIGraphNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.ToTable("ai_graph_nodes", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIKnowledgeArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("ai_knowledge_articles", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIKnowledgeCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ai_knowledge_collections", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIKnowledgeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId");

                    b.ToTable("ai_knowledge_units", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionsJson")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .HasColumnType("text")
                        .HasColumnName("icon_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<int>("BookingMode")
                        .HasColumnType("integer")
                        .HasColumnName("booking_mode");

                    b.Property<string>("CheckInInstructions")
                        .HasColumnType("text")
                        .HasColumnName("check_in_instructions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("text")
                        .HasColumnName("customer_note");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<string>("CustomerZalo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_zalo");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<string>("IdCardBackMaskedPath")
                        .HasColumnType("text");

                    b.Property<string>("IdCardBackPath")
                        .HasColumnType("text")
                        .HasColumnName("id_card_back_path");

                    b.Property<string>("IdCardFrontMaskedPath")
                        .HasColumnType("text");

                    b.Property<string>("IdCardFrontPath")
                        .HasColumnType("text")
                        .HasColumnName("id_card_front_path");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PaymentProofUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_proof_url");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int?>("RoomSlotInventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("room_slot_inventory_id");

                    b.Property<string>("SlotLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slot_label");

                    b.Property<string>("SmartLockCode")
                        .HasColumnType("text")
                        .HasColumnName("smart_lock_code");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_price");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("WifiPassword")
                        .HasColumnType("text")
                        .HasColumnName("wifi_password");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomSlotInventoryId");

                    b.HasIndex("UserId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<int>("BookingLeadTimeHours")
                        .HasColumnType("integer")
                        .HasColumnName("booking_lead_time_hours");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Hotline")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hotline");

                    b.Property<string>("MapUrl")
                        .HasColumnType("text")
                        .HasColumnName("map_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalImages")
                        .HasColumnType("text")
                        .HasColumnName("additional_images");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("ExtraGuestFee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("extra_guest_fee");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer")
                        .HasColumnName("max_guests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceHolidayPerDay")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_holiday_per_day");

                    b.Property<decimal>("PriceHolidayPerHour")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_holiday_per_hour");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_per_day");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_per_hour");

                    b.Property<decimal>("PriceWeekendPerDay")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_weekend_per_day");

                    b.Property<decimal>("PriceWeekendPerHour")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_weekend_per_hour");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date")
                        .HasColumnName("slot_date");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot_label");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TemplateId");

                    b.ToTable("room_slot_inventories", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    b.Property<string>("OverrideType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("override_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_slot_overrides", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanupMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cleanup_minutes");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("CrossesMidnight")
                        .HasColumnType("boolean")
                        .HasColumnName("crosses_midnight");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<TimeOnly?>("FixedEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fixed_end_time");

                    b.Property<TimeOnly?>("FixedStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fixed_start_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("SeedStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("seed_start_time");

                    b.HasKey("Id");

                    b.ToTable("room_slot_templates", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotTemplateAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TemplateId");

                    b.ToTable("room_slot_template_assignments", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.HasKey("Id");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("room_amenities", b =>
                {
                    b.Property<int>("amenity_id")
                        .HasColumnType("integer")
                        .HasColumnName("amenity_id");

                    b.Property<int>("room_id")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.HasKey("amenity_id", "room_id");

                    b.HasIndex("room_id");

                    b.ToTable("room_amenities", (string)null);
                });

            modelBuilder.Entity("WebHomestay.Models.AIGraphEdge", b =>
                {
                    b.HasOne("WebHomestay.Models.AIGraphNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHomestay.Models.AIGraphNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("WebHomestay.Models.AIKnowledgeArticle", b =>
                {
                    b.HasOne("WebHomestay.Models.AIKnowledgeCollection", "Collection")
                        .WithMany("Articles")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("WebHomestay.Models.AIKnowledgeUnit", b =>
                {
                    b.HasOne("WebHomestay.Models.AIBrainScope", "Scope")
                        .WithMany("KnowledgeUnits")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("WebHomestay.Models.ActivityLog", b =>
                {
                    b.HasOne("WebHomestay.Models.AdminUser", "AdminUser")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("WebHomestay.Models.AdminUser", b =>
                {
                    b.HasOne("WebHomestay.Models.Branch", "Branch")
                        .WithMany("StaffMembers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("WebHomestay.Models.Booking", b =>
                {
                    b.HasOne("WebHomestay.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHomestay.Models.RoomSlotInventory", "RoomSlotInventory")
                        .WithMany()
                        .HasForeignKey("RoomSlotInventoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebHomestay.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("RoomSlotInventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebHomestay.Models.Room", b =>
                {
                    b.HasOne("WebHomestay.Models.Branch", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotInventory", b =>
                {
                    b.HasOne("WebHomestay.Models.Room", "Room")
                        .WithMany("SlotInventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHomestay.Models.RoomSlotTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotOverride", b =>
                {
                    b.HasOne("WebHomestay.Models.Room", null)
                        .WithMany("SlotOverrides")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebHomestay.Models.RoomSlotTemplateAssignment", b =>
                {
                    b.HasOne("WebHomestay.Models.Room", "Room")
                        .WithMany("SlotAssignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHomestay.Models.RoomSlotTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("room_amenities", b =>
                {
                    b.HasOne("WebHomestay.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("amenity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHomestay.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebHomestay.Models.AIBrainScope", b =>
                {
                    b.Navigation("KnowledgeUnits");
                });

            modelBuilder.Entity("WebHomestay.Models.AIGraphNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("WebHomestay.Models.AIKnowledgeCollection", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("WebHomestay.Models.AdminUser", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("WebHomestay.Models.Branch", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("WebHomestay.Models.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("SlotAssignments");

                    b.Navigation("SlotInventories");

                    b.Navigation("SlotOverrides");
                });

            modelBuilder.Entity("WebHomestay.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
